### ISSUE TITLE
ImportError: No module named tabulate

### ISSUE THREAD

**Issue by shaz13** [amarlearning/PyStalker#2]
Run error while executing it locally. Please update the demo for dependencies involved. 
@amarlearning 
![screenshot from 2017-04-01 17-20-33](https://cloud.githubusercontent.com/assets/24438869/24578536/8826596c-16ff-11e7-85fc-09e6975fd54b.png)

**Comment by amarlearning** [comment]
@shaz13 Thanks for pointing out that! :smile: 
I have updated the `Readme.md` file accordingly.

You can install the dependencies by this command `pip install -r requirements.txt`

**Comment by shaz13** [comment]
@amarlearning  You are welcome. Closing the issue :+1:
