### ISSUE TITLE
Traceback(most recent,call last)

### ISSUE THREAD

**Issue by priyanshugandhi** [amarlearning/PyStalker#3]
when you try to enter any user name, it gives following error:
Traceback(most recent,call last)
I/O error: no such file or driectory:

**Comment by amarlearning** [comment]
@priyanshugandhi A file named `DATA` should be added to the root directory. Do you want to open a PR for that?

**Comment by priyanshugandhi** [comment]
Yes @amarlearning

**Comment by amarlearning** [comment]
@priyanshugandhi you need to add the DATA file only
